version: '3'
services:
  mythbackend:
    build: .
    environment:
      - CONFIG_MODE=1
    volumes:
      - config:/home/mythtv:nocopy
      - data:/var/lib/mysql:nocopy
      - media:/var/lib/mythtv:nocopy
      - ./shared:/shared
    hostname: mythbackend
    network_mode: "host"
    ports:
      - "6506:6506"
      - "6543:6543"
      - "6544:6544"
      - "6554:6554"
      - "6570:6570"
      - "6580:6580"
volumes:
  config:
  data:
  media:
