#!/usr/bin/with-contenv bash

export HOME=/home/mythtv

RET=1
while [[ RET -ne 0 ]]; do
    mysql -uroot -e "status" > /dev/null 2>&1
    RET=$?
    sleep 2s
done

exec /usr/bin/mythbackend --user mythtv --logpath /var/log/mythtv --pidfile /var/run/mythtv/mythtv.pid